language: csharp
sudo: required
dist: precise
solution: source/UTMGenerator.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore source/UTMGenerator.sln
after_script:
  - nunit-console source/UTMGeneratorTests/bin/Release/UTMGeneratorTests.dll