image: Visual Studio 2015
platform: Any CPU
configuration: Release

branches:
  only:
    - master

build:
  project: source/UTMGenerator.sln

before_build:
  - nuget restore source/UTMGenerator.sln

test:
  assemblies:
    only:
      - source/UTMGeneratorTests/bin/Release/UTMGeneratorTests.dll